// Generated by AI

const { spawn } = require('child_process');

class fixLua {
	createUserPath = (cmd) => spawn(cmd, {shell: true, stdio: ['pipe', 'pipe', 'pipe']});
}

exports('fixSandbox', () => ({
	createUserPath: (cmd) => new fixLua().createUserPath(cmd)
}));